### ISSUE TITLE
i just build ，using cmake

### ISSUE THREAD

**Issue by XiaoChang0519** [kelbon/AnyAny#13]
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(500): error C2947: 应由“>”终止 模板参数列表，却找到“<”
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(503): note: 查看指向正在编译的变量模板“const size_t aa::vtable<aa::size_of,aa::destroy,example::call<void __cdecl(int,float,double)>::method,aa::copy,aa::move>::number_of_method<aa::copy_with<std::allocator<enum std::byte>,40>::method>”的引用
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(928): note: 查看指向正在编译的变量模板“const bool aa::vtable<aa::size_of,aa::destroy,example::call<void __cdecl(int,float,double)>::method,aa::copy,aa::move>::has_method<aa::copy_with<std::allocator<enum std::byte>,40>::method>”的引用
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(929): note: 查看指向正在编译的变量模板“const bool aa::basic_any<aa::any_with_t<std::allocator<enum std::byte>,40,aa::size_of,aa::destroy,example::call<void __cdecl(int,float,double)>::method,aa::copy,aa::move>,std::allocator<enum std::byte>,40,aa::size_of,aa::destroy,example::call<void __cdecl(int,float,double)>::method,aa::copy,aa::move>::has_method<aa::copy_with<std::allocator<enum std::byte>,40>::method>”的引用
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(1409): note: 查看对正在编译的 类 模板 实例化“aa::basic_any<aa::any_with_t<std::allocator<std::byte>,40,aa::size_of,aa::destroy,example::call<R (Head,float,double)>::method,aa::copy,aa::move>,Alloc,40,aa::size_of,aa::destroy,example::call<R (Head,float,double)>::method,aa::copy,aa::move>”的引用
[build]         with
[build]         [
[build]             R=void,
[build]             Head=int,
[build]             Alloc=std::allocator<std::byte>
[build]         ]
[build] C:\Users\16705\Desktop\AnyAny\examples\functional_paradigm.hpp(37): note: 查看对正在编译的 类 模板 实例化“aa::any_with_t<std::allocator<std::byte>,40,aa::size_of,aa::destroy,example::call<R (Head,float,double)>::method,aa::copy,aa::move>”的引用
[build]         with
[build]         [
[build]             R=void,
[build]             Head=int
[build]         ]
[build] C:\Users\16705\Desktop\AnyAny\examples\functional_paradigm.hpp(75): note: 查看对正在编译的 类 模板 实例化“example::basic_function<void (int,float,double),aa::copy,aa::move>”的引用
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(500): error C3203: "copy": 未指定的 别名 模板 不能用作 模板 参数 "Args" 的 模板 参数，应为真实类型
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(500): error C2143: 语法错误: 缺少“;”(在“'symbol'”的前面)
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(500): error C2059: 语法错误:“'symbol'”
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(500): error C3376: “aa::vtable<aa::size_of,aa::destroy,example::call<R (Head,float,double)>::method,aa::copy,aa::move>::number_of_method”: 只允许使用静态数据成员模板
[build]         with
[build]         [
[build]             R=void,
[build]             Head=int
[build]         ]
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(500): error C2062: 意外的类型“unknown-type” 
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(503): error C3376: “aa::vtable<aa::size_of,aa::destroy,example::call<R (Head,float,double)>::method,aa::copy,aa::move>::has_method”: 只允许使用静态数据成员模板
[build]         with
[build]         [
[build]             R=void,
[build]             Head=int
[build]         ]
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(503): error C2062: 意外的类型“unknown-type” 
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(928): error C3376: “aa::basic_any<aa::any_with_t<std::allocator<std::byte>,40,aa::size_of,aa::destroy,example::call<R (Head,float,double)>::method,aa::copy,aa::move>,Alloc,40,aa::size_of,aa::destroy,example::call<R (Head,float,double)>::method,aa::copy,aa::move>::has_method”: 只允许使用静态数据成员模板
[build]         with
[build]         [
[build]             R=void,
[build]             Head=int,
[build]             Alloc=std::allocator<std::byte>
[build]         ]
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(928): error C2062: 意外的类型“unknown-type” 
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(929): error C2789: “aa::basic_any<aa::any_with_t<std::allocator<std::byte>,40,aa::size_of,aa::destroy,example::call<R (Head,float,double)>::method,aa::copy,aa::move>,Alloc,40,aa::size_of,aa::destroy,example::call<R (Head,float,double)>::method,aa::copy,aa::move>::has_copy”: 必须初始化常量限定类型的对象
[build]         with
[build]         [
[build]             R=void,
[build]             Head=int,
[build]             Alloc=std::allocator<std::byte>
[build]         ]
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(929): note: 参见“aa::basic_any<aa::any_with_t<std::allocator<std::byte>,40,aa::size_of,aa::destroy,example::call<R (Head,float,double)>::method,aa::copy,aa::move>,Alloc,40,aa::size_of,aa::destroy,example::call<R (Head,float,double)>::method,aa::copy,aa::move>::has_copy”的声明
[build]         with
[build]         [
[build]             R=void,
[build]             Head=int,
[build]             Alloc=std::allocator<std::byte>
[build]         ]
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(929): error C2238: 意外的标记位于“;”之前
[build] C:\Users\16705\Desktop\AnyAny\include\anyany.hpp(932): fatal error C1903: 无法从以前的错误中恢复；正在停止编译
[build] ninja: build stopped: subcommand failed.
[build] Build finished with exit code 1

**Comment by kelbon** [comment]
1. i can't read chinese
2.  if you use msvc, use clang-cl (in VS22)

**Comment by XiaoChang0519** [comment]
thanks you，i use msvc in windows to compile，now i know the reason
