### ISSUE TITLE
Do you see a way to add associated types?

### ISSUE THREAD

**Issue by uselessgoddess** [kelbon/AnyAny#18]
For example, it might look something like this:
```c++
template <typename T>
struct Deref {
  struct Target {};

  static auto do_invoke(const T&) -> Target&;

  template <typename CRTP>
  struct plugin {
    auto deref() const {
      return aa::invoke<Deref>(*static_cast<const CRTP*>(this));
    }
  };
};

template <typename Ptr>
struct Deref<std::shared_ptr<Ptr>> {
  using Target = std::remove_extent_t<Ptr>;

  static auto do_invoke(const std::shared_ptr<Ptr>& self) -> Target& {
    return *self.get();
  }
};
```
This is convenient because Self is responsible for the associated type itself. 
In this example, the opposite is true
https://github.com/kelbon/AnyAny/blob/c4603b3959c5f8e8b9a104b09bb53025b1ff776f/examples/functional_paradigm.hpp#L22-L30

However, it doesn't work because result_t get return type from `Method<aa::interface_t>`, but `Target` is unique for all types.
This can be fixed, but for dyn call via `poly_ref`/`any_` it will require explicit aanotation

**Comment by kelbon** [comment]
> For example, it might look something like this:
> 
> ```c++
> template <typename T>
> struct Deref {
>   struct Target {};
> 
>   static auto do_invoke(const T&) -> Target&;
> ```
May be you can require typename T::Target;
But anyway you need to return same type for all, so Target need to be same for all types, so its useless. (i think rust has same requirements for Dyn traits, apart from the fact that rust has no cast to smaller requirements)

**Comment by uselessgoddess** [comment]
> But anyway you need to return same type for all, so Target need to be same for all types, so its useless.

It's not useless. For example, any type that was written in the `type_traits` style can be rewritten.
In Rust and Swift, they really have more privileges. Dyn constraint really stricter.

Associated types will reverse the implementation. This helps to better perceive where this type comes from. 
- outsize - template param (we pass result type to get result)
- insized - associated param (we pass another type to get result)

Also compare :)
```c++
template <typename T>
struct Iterator {
  struct Item {};

  static auto do_invoke(const T&) -> std::optional<Item>;

  template <typename CRTP>
  struct plugin {
    auto next() const {
      return aa::invoke<Iterator>(*static_cast<const CRTP*>(this));
    }
  };
};

template <>
struct Iterator<MyIter> {
  using Item = std::size_t;

  static auto do_invoke(const MyIter& self) -> std::optional<Item> {
    // impl
  }
};

. . .

// i hope it works))
template<typename Item>
struct Constraints {
  template <typename T>
  struct iterator {
    static auto do_invoke(const T&) -> std::optional<Item>;

    template <typename CRTP>
    struct plugin {
      auto next() const {
        return aa::invoke<Iterator>(*static_cast<const CRTP*>(this));
      }
    };
  };
};

template<>
struct Constraints <std::size_t> {
  template<typename T>
  struct iterator {
    static auto do_invoke(const T&) -> std::optional<std::size_t> {
      // impl
    }
  };
};
```

**Comment by uselessgoddess** [comment]
Although maybe it really doesn't make sense

**Comment by uselessgoddess** [comment]
Can you show how you see interfaces with template parameters?
I can do it somehow like this: [**godbolt**](https://godbolt.org/z/drve49dKz)
But I'm sad that I can't use `Method<Self>::Type`
We need to know the `Type`

Probably it possible with `static_ref`, but i'm not C++ programmer to make this code work
```c++
template <typename Output>
using Oof = /* template<typename Self> Foo<Self, Output>*/;

template <typename Self, typename Output>
auto foo(aa::static_ref<Self, Oof<Output>>& ref) {
}
```

**Comment by uselessgoddess** [comment]
> > Can you show how you see interfaces with template parameters?
> 
> ```c++
> template<typename A, typename B>
> struct foo {
>   template<typename T>
>   struct trait {
>     static X do_invoke(T& self) { return X{}; } 
>   };
> };
> 
> template<typename T>
> using trait_foo_int_double = foo<int, double>::template trait;
> // or
> using h = any_with<foo<int, double>::template trait>;
> ```


Oh, no. Here is an example from [godbolt](https://github.com/kelbon/AnyAny/issues/18#issuecomment-1201118771), but with this style - https://godbolt.org/z/b8jK4bPK8

**Comment by uselessgoddess** [comment]
Oh no, bro. When I have time, I will definitely try to make it.

**Comment by kelbon** [comment]
> Oh no, bro. When I have time, I will definitely try to make it.
I don't remember exactly what the discussion was, but I'm just throwing off a random thought here 
```C++
template<typename T>
struct trait {
  static void do_invoke(T& self);

  template<typename U = T>
  consteval auto associated_type() {
    return std::type_identity<U::type>{}; 
  }
};
```
