### ISSUE TITLE
Interfaces & Specializations or "More than just Duck Typing"

### ISSUE THREAD

**Issue by AVasK** [kelbon/AnyAny#3]
First of all, your Any syntax looks awesome, especially when compared to other C++ type-erasure libraries (folly.Poly and Dyno are but two examples of how convoluted the syntax can become). Lots of respect for the great idea!

The whole thing reminded me of Rust's Traits, except for the fact that Rust enforces the explicit 'impl' to ensure that the class indeed satisfies the trait as opposed to mere coincidence in method naming between absolutely different classes. 
Now, to the proposal: First, we can add the Interfaces (optionally) as nested structs inside the class, i.e.:
```C++
template <class T>
struct Drawable {
    // Interface
    template <class Base>
    struct Interface : Base {
        void draw() noexcept {
            this->template invoke<Drawable>();
        }
    };

    // Generic Implementation
    static void invoke(T const& self) noexcept {
        self.draw();
    }
};
```
This way any<Drawable> will automagically inherit the .draw() simply chaining the interface inheritance (albeit, with some template magic in place to make it truly optional) when such Interface is present in the Drawable class. This also eases the burden of re-implementing it ourselves every time, since I believe we'd like to have some 'Methods' multi-purpose and available as mix-in traits.

And this also gives us the second option: now we can achieve something very similar to Rust's traits -- we may only specify the interface and then it's mandatory for the programmer to specialise the Method (as an extension) for their class, like that:
```C++
template <class T>
struct Drawable {
    // Interface only
    template <class Base>
    struct Interface : Base {
        void draw() noexcept {
            aa::invoke<Drawable>(*this);
        }
    };
};


extern struct my_class;

template <> struct Drawable<my_class>
{
    static void invoke(my_class & self) noexcept {
        ...
    }
};
```

**Comment by kelbon** [comment]
> as opposed to mere coincidence in method naming between absolutely different classes.

It also must accept same arguments and return same type =)
In fact, at this stage, the problems can only be semantic, which are not checked at compilation - like with different types of iterators(input / forward)

In general idea with interface in methods is good, but there are some problems - code dublicating and methods can use same names (overload), but its impossible to handle it in this case. Its not a big problem, but...

And it cant be `struct Interface : Base` like in folly polly, because then it must be one Interface which inherit from Base. In anyany with many methods it will be virutal inheriting or ambiguity. But it can be CRTP or deducing this(C++23).

So... I called it 'plugin' (because its only part and 'interface' highlighted as keyword in VS studio xD)
```C++
template <typename T>
struct Draw {

  template <typename CRTP>
  struct plugin {
    void draw(std::ostream& out, int val) const {
      aa::invoke<DrawExplicit>(*static_cast<const CRTP*>(this), out, val);
    }
  };

  static void do_invoke(T self, std::ostream& out, int val) {
    self.draw(out, val);
  }
};
```
What about explicit interface... I thought about it, you always can do smth like
```C++
template<typename>
struct Foo;

template<>
struct Foo<aa::interface_t> {
  static void do_invoke(aa::interface_t& self, int arg);
};
```
So programmer will be forced to specialize method for his type

But i added an another way to explicit subscribe to Method:

```C++
template <typename T>
struct Bar {

  using explicit_interface = void;

  static void do_invoke(T self, float& a, int b) {
    self.bar(a, b);
  }
};

struct MyType {
...
using satisfies = aa::satisfies<Bar>;
};
OR
namespace aa {
  template<>
  constexpr inline bool satisfies_v<MyType, Bar> = true;
}

```

You can see it in https://github.com/kelbon/AnyAny/pull/4

**Comment by AVasK** [comment]
Great :)

> It also must accept same arguments and return same type =)
In fact, at this stage, the problems can only be semantic, which are not checked at compilation - like with different types of iterators(input / forward)

To clarify, I don't have any problems with Duck Typing as it is, it's just that it's a relatively common objection to duck typing in general, or at least I've heard it quite a lot) And since just not providing a generic implementation in the Method makes explicit specialisation somewhat more mandatory, I thought it'd be a nice point essentially for free (no implementation cost). But I see you took it a step further and added another way to express that more precisely xD

> In general idea with interface in methods is good, but there are some problems - code dublicating and methods can use same names (overload), but its impossible to handle it in this case. Its not a big problem, but...

Yeah, speaking of code duplication, I agree, it's a little unpleasant. But (if)when we get the reflection system in C++ (still hoping for C++23) this may as well become a solvable problem, e.g. I believe we'd be able to just write an interface and auto-generate the do_invoke() version at least for the general case)

Could you please elaborate a bit on this one?
>and methods can use same names (overload)

>And it cant be struct Interface : Base like in folly polly, because then it must be one Interface which inherit from Base. In anyany with many methods it will be virutal inheriting or ambiguity. But it can be CRTP or deducing this(C++23).

I originally implemented it via chain inheritance :) 
I made a small custom any implementation for that, so it may be possible due to some divergence in implementation?
(here, `trait` is what you defined as `TTS` )
```C++
namespace detail {
        
    template <trait Trait, class=meta::check_valid> // works like void works with a void_t
    struct has_interface { static constexpr bool value = false; };

    template <trait Trait>
    struct has_interface<Trait, meta::is_valid< // works like void_t
        typename Trait<dummy>::template Interface<dummy>
    >> { static constexpr bool value = true; };

    template <trait Trait, class Interfaces>
    struct this_interface {
        using type = typename Trait<dummy>::template Interface< Interfaces >;
    };

    template <class Any, trait... Traits> struct interfaces;

    template <class Any, trait Trait, trait... Traits>
    using select_interface = typename std::conditional<
        has_interface<Trait>::value,
        this_interface< Trait, interfaces<Any, Traits...> >,
        std::type_identity< interfaces<Any, Traits...> >
    >::type;

    template <class Any, trait Trait, trait... Traits>
    struct interfaces<Any, Trait, Traits...> 
    : select_interface<Any, Trait, Traits...>
    {
        using Base = select_interface<Any, Trait, Traits...>;
        using Base::Base;
    };

    template <class Any>
    struct interfaces<Any> : Any { using Any::Any; };

} // namespace detail

template <trait... Traits>
class any : public detail::interfaces<any_base<Traits...>, Traits...>  {
```
But then given what a templated mess it becomes, I thought I'd better not post it xD
And then I saw your CRTP solution, I didn't even think about it... But it looks pretty nice, especially the code is cleaner) The only possible downside is that `struct Interface : Base` is simpler to define a macro for, but I guess it's not a problem since we're using the modern C++ and macros are considered harmful :)

**Comment by kelbon** [comment]
>> Could you please elaborate a bit on this one?

>and methods can use same names (overload)

For example we have two methods with plugins and first method declares .Foo(int) and second declares .Foo(double), then if we inherit from first and second plugin we will have no Foo method because its ambigious.
We can write
```C++
using Plugin1::Foo;
using Plugin2::Foo;
```
But without reflection its impossible
> I originally implemented it via chain inheritance :)
Its very interesting, but recursion is slow)
