### ISSUE TITLE
Remove macro leakage

### ISSUE THREAD

**Issue by Anton3** [kelbon/AnyAny#42]
We'd like to use the library at [userver][1], but currently can't, because we have a policy against leakage of any macros from our headers that are not `USERVER_` prefixed.

At least, we can't use `aa::any` to store user types as an implementation detail, which is where aa is most useful.

- [x] Remove or `#undef` all implementation-detail macros
- [x] Move public macros to a separate header
- [x] Adopt `AA_UPPER_CASE` or `ANYANY_UPPER_CASE` naming style

[1]: https://github.com/userver-framework/userver

**Comment by kelbon** [comment]
now macros are in separate header anyany/anyany_macro.hpp and others are #undef'ed
