### ISSUE TITLE
Remove extra includes

### ISSUE THREAD

**Issue by Anton3** [kelbon/AnyAny#45]
The library should ideally be usable in common headers that permeate throughout a given project. Heavy includes can mean a heavy compilation performance hit in such cases.

Consider at least removing `<array>`, as it includes `<algorithm>`.

Consider reviewing all the other heavy includes and seeing if it's possible to go by without them:
- `<functional>`
- `<memory>`
- `<optional>`
- `<stdexcept>`

(Those are considered heavy according to [C++ Compile Health Watchdog][1].)

[1]: https://artificial-mind.net/projects/compile-health/

**Comment by kelbon** [comment]
Header  anyany/anyany.hpp now only depends on

 <cassert>, <exception>, <utility>, <type_traits>, <cstddef>
