### ISSUE TITLE
Remove `::template method` ugliness when using templated Methods

### ISSUE THREAD

**Issue by Anton3** [kelbon/AnyAny#47]
See a snippet from examples:

```cpp
template<typename Signature>
using function_ref = aa::poly_ref<aa::call<Signature>::template method>;
```

This is required because AnyAny works with template template parameters.

It wouldn't be required if we slightly modified the way _Methods_ are defined.

Before:

```cpp
template <typename T>
struct Foo {
  static void do_invoke(T&) { ... }

  template <typename CRTP>
  struct plugin {
    void foo() const { ... }
  };
};
```

After:

```cpp
struct Foo {
  template <typename T>
  static void do_invoke(T&) { ... }

  template <typename CRTP>
  struct plugin {
    void foo() const { ... }
  };
};
```

It has the additional benefit that it forces `plugin` not to depend on `T`, purely syntactically.

**Comment by kelbon** [comment]
Method now is a typename and not template<typename> typename
