### ISSUE TITLE
Allow grouping Methods into bundles (interfaces, prototypes, traits)

### ISSUE THREAD

**Issue by Anton3** [kelbon/AnyAny#48]
We can upcast `any<A, B, C>` to `any<A, B>` and `any<A, C>`, but not to `any<A, C>`.

This limitation can break diamond dependencies. For example, assume that place1 requires `AA1 = poly_ref<A, B>`, place2 requires `AA2 = poly_ref<A, C>`, place3 requires `AA3 = poly_ref<A, D>`. Here `A` can be a common _Method_ like `destroy` or `copy`. It's currently impossible to create an `any` that can be upcast to all of those.

Additionally, bundles of _Methods_ are useful to remove code duplication.

```cpp
struct Metric : aa::interface<InitializeMetric, WriteMetric> {};

struct ResettableMetric : aa::interface<ResetMetric> {};
```

**Comment by kelbon** [comment]
It's very unintuitive for the user, and it's hugely expensive for the compiler, so it's not enabled by default.

But I added

```C++
template<typename... MethodOrInterfaceAlias>
using interface_alias = ...;
template <template <typename...> typename Template, typename... Methods>
using insert_flatten_into = ...;

```

So you can create your aliases:

```C++
template<typename... Ts>
using any_supporting_interfaces = aa::insert_flatten_into<aa::any_with, Ts...>;

using input_range_interface = aa::interface_alias<next, done>;
using random_access_range_interface = aa::interface_alias<input_range_interface, at, get_current>;

using my_range = any_supporting_interfaces<random_access_range_interface, aa::copy, aa::equal_to>;
```
