### ISSUE TITLE
MSVC problems

### ISSUE THREAD

**Issue by kamrann** [kelbon/AnyAny#57]
Just wondering if you've given up trying to maintain MSVC support? I notice the CI doesn't appear to be building with it.
I recently updated `anyany` to latest after having been using a fairly old version, and my codebase is just blowing up with ICEs everywhere on MSVC, both `14.37` and `14.38` toolchains (no issues when building with Clang).

**Comment by kelbon** [comment]
> [kamrann](/kamrann)

I'm testing msvc locally on my PC because it's too uncomfortable to do it via CI. And it works, but msvc really likes to give unexpectedly stupid errors, can you show some code examples?

**Comment by kamrann** [comment]
Still trying to reduce down a repro. It's possible I'm doing something unintended with `poly_ref` as it wasn't in the library before I updated - I've tried to make use of it in my refactoring but not entirely sure I'm using it correctly. Obviously MSVC shouldn't crash regardless.

Will update when I have something simple.

**Comment by kamrann** [comment]
So given I've spent the entire day fiddling trying to work out what's going on, this is maybe the most ridiculously simple repro I've ever whittled something down to. So simple I'm wondering if I have some local corruption or something. This crashes MSVC for me, can you confirm?
```
#include "anyany/anyany.hpp"

void boom(aa::any_with<>)
{}
```
Note that adding a method and/or `aa::move`/`aa::copy` makes no difference. It's triggered specifically by a function taking an `any_with` by value.

**Comment by kelbon** [comment]
> So given I've spent the entire day fiddling trying to work out what's going on, this is maybe the most ridiculously simple repro I've ever whittled something down to. So simple I'm wondering if I have some local corruption or something. This crashes MSVC for me, can you confirm?
> 
> ```
> #include "anyany/anyany.hpp"
> 
> void boom(aa::any_with<>)
> {}
> ```
> 
> Note that adding a method and/or `aa::move`/`aa::copy` makes no difference. It's triggered specifically by a function taking an `any_with` by value.

Lol, it rly breaks msvc. I have MAAANY functions using any_with in tests, but they are working...

**Comment by kamrann** [comment]
Yeah it's ridiculously sensitive to the context it seems, I've got a bunch of code that seems to do fundamentally the same thing yet is compiling fine...

**Comment by kamrann** [comment]
Thanks, still got a fair bit of uncommenting things I disabled to do before I can be sure, but looks like that is indeed working.

I thought I had a different issue relating to `poly_ref` but it seems it was actually the same thing as the above. Can I just confirm about its usage though - is the idea that I can construct one from a raw reference to any object implementing the method set? And it appears I can't construct an `any_with<>::ref` from an existing `any_with<>`, is that intentional?

**Comment by kelbon** [comment]
> Thanks, still got a fair bit of uncommenting things I disabled to do before I can be sure, but looks like that is indeed working.
> 
> I thought I had a different issue relating to `poly_ref` but it seems it was actually the same thing as the above. Can I just confirm about its usage though - is the idea that I can construct one from a raw reference to any object implementing the method set? And it appears I can't construct an `any_with<>::ref` from an existing `any_with<>`, is that intentional?

Yes, you can construct any::ref without 'any' object, like 'string_view' without 'string'.
You can create 'ref' from 'any' by dereferencing pointer

any_with<...> x = something;
decltype(x)::ref r = *&x;

There are no implicit creation reference from any, because 'any' can be empty and reference guaranteed to be not empty

**Comment by kamrann** [comment]
Got it, thank you for the explanation!
