### ISSUE TITLE
Issues with forward declarations/mutual dependencies

### ISSUE THREAD

**Issue by kamrann** [kelbon/AnyAny#58]
Recently I've expanded my use of the library in my codebase, but as a result I'm running into some headaches. In particular, through its method concept checking and the use of `int` as a kind of placeholder type, I keep hitting cases where it gets extremely difficult to arrange my code in an acceptable way. What I'm not sure of is if I'm hitting inevitable limitations of this approach to polymorphism, or if it's just my own misuse/bad design.

Here's an example. Consider the following fairly simple pattern in typical object-oriented code. Two types with mutual dependencies in their interfaces:

```
class BaseA;
class BaseB;

class BaseA
{
public:
    virtual void do_something(BaseB const&) = 0;
};

class BaseB
{
public:
    virtual BaseA* get_thing() const = 0;
};
```

Can I somehow achieve the same thing when using `poly_ref` as my polymorphic interface?
I can't do the following as it won't accept an incomplete type.
```
struct MethodB;
using RefB = aa::poly_ref< MethodB >;
```

But in order to define `MethodB` as follows
```
struct MethodB
{
    template < typename T >
    static auto do_invoke(T const& x) -> RefA
    {
        return x.get_thing();
    }
};
```
I need `RefA`, which requires `MethodA`, which requires `RefB`...
Am I missing something obvious?

**Comment by kelbon** [comment]
Its only concepts problem, i may add possibility to disable concepts, but C++ needs a way to forward declare structs like this:

```C++
aa::method struct Abc;

template<...>
std::random_access_range struct vector;

```
Etc, only reason why incomplete type do not work - concepts

**Comment by kelbon** [comment]
> Can I somehow achieve the same thing when using `poly_ref` as my polymorphic interface? I can't do the following as it won't accept an incomplete type.
> 
> ```
> struct MethodB;
> using RefB = aa::poly_ref< MethodB >;
> ```
> 
> But in order to define `MethodB` as follows
> 
> ```
> struct MethodB
> {
>     template < typename T >
>     static auto do_invoke(T const& x) -> RefA
>     {
>         return x.get_thing();
>     }
> };
> ```
https://github.com/kelbon/AnyAny/commit/cdcd17c8b9c10d6962fc6e63239feb92af043ac4

There are different ways to do it, but i  just added option to disable concepts while C++ does not have good solution

I

**Comment by kamrann** [comment]
Okay yep makes sense. I don't suppose there's any way it could be refactored to defer the concept checks instead of dropping them entirely?

It seems `anyany` is doing it eagerly, if I'm not mistaken merely declaring `using X = aa::poly_ref< MyMethod >;` triggers instantiation of `MyMethod::do_invoke< int >` (side note: I think this is also why I get unexpected errors about `int` not being a class type if I use deduced `auto` return type in the method definition). I'm just wondering if somehow instantiation/concept check could be deferred, maybe to the point in code where `invoke` is used? Note I really have no idea about the implementation details, I'm just speculating.

**Comment by kelbon** [comment]
> Okay yep makes sense. I don't suppose there's any way it could be refactored to defer the concept checks instead of dropping them entirely?
> 
> It seems `anyany` is doing it eagerly, if I'm not mistaken merely declaring `using X = aa::poly_ref< MyMethod >;` triggers instantiation of `MyMethod::do_invoke< int >` (side note: I think this is also why I get unexpected errors about `int` not being a class type if I use deduced `auto` return type in the method definition). I'm just wondering if somehow instantiation/concept check could be deferred, maybe to the point in code where `invoke` is used? Note I really have no idea about the implementation details, I'm just speculating.

Deferring concept check will remove all advantages from concepts, when you declare using X = poly_ref<Method> concept tries to instanciate with 'Method' to check if type 'poly_ref<Method>' is valid, concept does not sees signature of method for vtable and searches 'Method::signature_type', but you dont have it, so its tries instanciate 'do_invoke' with 'int' as example type,  because its required that signature must not be dependent on type (as for virtual functions)

**Comment by kelbon** [comment]
> 

I will think about it latter and may be remove concepts from struct declarations or check on dctors / static asserts instead

**Comment by kelbon** [comment]
Thank you for your feedback, i disabled concepts on struct declarations, because at this point its not required, that Methods are complete types, but concepts itself is present for user defined functions or as doc for 'what Method is'

https://github.com/kelbon/AnyAny/pull/61

Can you tell how you use the library and what problems/benefits you see?
