### ISSUE TITLE
MSVC: Attribute msvc::no_unique_address missing brackets

### ISSUE THREAD

**Issue by Thiesius** [kelbon/AnyAny#73]
I'm currently testing the library, and I'm using MSVC. However I had a minor hiccup trying to compile my code with anyany.hpp

This is the offensive line:
https://github.com/kelbon/AnyAny/blob/65c7a77f64a52881981ebee84eb31610fe6e7db9/include/anyany/anyany.hpp#L35
I just added the brackets and it works.
`#define ANYANY_NO_UNIQUE_ADDRESS [[msvc::no_unique_address]]`

I'm currently using the MSVC Preview, but should have those brackets according to MSVC docs. This looks like "Forgotten after refactor".

(I understand by your bug report in VS Dev Community that the attribute probably doesn't work correctly anyways,  but I'm currently more interested in just trying the library, so the increased size doesn't bother me)

**Comment by kelbon** [comment]
> I'm currently testing the library, and I'm using MSVC. However I had a minor hiccup trying to compile my code with anyany.hpp
> 
> This is the offensive line:
> 
> https://github.com/kelbon/AnyAny/blob/65c7a77f64a52881981ebee84eb31610fe6e7db9/include/anyany/anyany.hpp#L35
> 
> 
> I just added the brackets and it works.
> `#define ANYANY_NO_UNIQUE_ADDRESS [[msvc::no_unique_address]]`
> I'm currently using the MSVC Preview, but should have those brackets according to MSVC docs. This looks like "Forgotten after refactor".
> 
> (I understand by your bug report in VS Dev Community that the attribute probably doesn't work correctly anyways, but I'm currently more interested in just trying the library, so the increased size doesn't bother me)

Oh, it is stuped error, thank for issue
