### ISSUE TITLE
Errors with aa::copy and assignment operator

### ISSUE THREAD

**Issue by kamrann** [kelbon/AnyAny#8]
The following simple snippet is resulting in compilation errors (on both MSVC and Clang):
```
using MyAny = aa::any_with< aa::copy >;

int main()
{
    auto a = MyAny{ 10 };
    auto b = a; // Works, but this is copy-constructor call
    b = a; // This is copy-assignment operator, and fails to compile

    return 0;
}
```
It appears that copy-construction works, but not copy-assignment.

**Comment by kamrann** [comment]
Aha, ok. So as a default, I should generally specify both `aa::move` and `aa::copy` if I want the any to inherit whatever copy/move functionality is available on the types I put into it?

I actually had both specified initially, but I removed `move` in an attempt to simplify a repro for errors I was getting. But perhaps the original errors were just a result of MSVC issues.

**Comment by kelbon** [comment]
> if I want the any to inherit whatever copy/move functionality is available on the types I put into it?

Yes, but for me default is only move(in many cases it is enough). 
Also may be you are interested in functional, which is not in readme yet,
https://github.com/kelbon/AnyAny/blob/06ad57a7df17305d96ede968d2733dd1193d8586/examples/basic_usage.hpp#L76
(plugins for interface parts, for example method ABC will add operator* or .ABC method without writing your type any_ and inheriting)
