### ISSUE TITLE
Cross-dynamic library compatibility

### ISSUE THREAD

**Issue by kamrann** [kelbon/AnyAny#9]
Sorry to flood you with issues ;)
This one might be a killer for me on my current project unfortunately; though it's probably not all that surprising, and is not really an issue per-se since this stuff lies outside of the core C++ language. 

I'm getting failing `any_cast`s, and I suspect it's caused by putting a value into an `any` in one dll, and then trying to extract it within another. I guess the comparison on the `vtable_ptr` is the culprit, since presumably each dll has its own copy of the instantiated `vtable_for` template, thus incompatible addresses? My suspicion is this is something that there's really no viable solution for, but maybe you have some ideas for a workaround?

Very similar issue with [this library](https://github.com/WG21-SG14/SG14/issues/170), some relevant info in that thread.

**Comment by kelbon** [comment]
I think problem is because you compile it separatelly, so one any type has two different vtable pointers
You can try to explicitly instanciate all of needed any s like
```cpp
template struct aa::any<CRTP, aa::copy, aa::move>;
...
```
Compile it and link to all other parts.

**Comment by kamrann** [comment]
I had the same idea (actually I tried explicit instantiation of `aa::vtable`), MSVC ICEd so I gave up ;)

Though it occurred to me that this comparison is actually only required to enable the bad cast exception. It might be nice if you were able to add an 'unsafe' version/overload for `any_cast` which simply omitted this check and was UB in the case of type mismatch. That way, it's possible to do what I'm trying, and it's on me if I screw things up!

Long term though, I think I should just find a way to avoid passing things over dll boundaries. It's too troublesome in general.

**Comment by kelbon** [comment]
> I had the same idea (actually I tried explicit instantiation of `aa::vtable_for`), MSVC ICEd so I gave up ;)
> 
> Though it occurred to me that this comparison is actually only required to enable the bad cast exception. It might be nice if you were able to add an 'unsafe' version/overload for `any_cast` which simply omitted this check and was UB in the case of type mismatch. That way, it's possible to do what I'm trying, and it's on me if I screw things up!
> 
> Long term though, I think I should just find a way to avoid passing things over dll boundaries. It's too troublesome in general.

Hi again, can you check if this solves your problems?
https://github.com/kelbon/AnyAny/pull/10
#define AA_DLL_COMPATIBLE before include anyany.hpp header and check
(better to use clang-cl in VS studio if you get internal compiler error on MSVC)
![image](https://user-images.githubusercontent.com/58717435/172652969-99d16acd-9c42-487d-9750-e1acd244135f.png)
